### ISSUE TITLE
Were you able to get video streaming working?

### ISSUE THREAD

**Issue by amarantedaniel** [Igor-Khomich/JanusAudioStreamPlayer#2]
Hi, first of all I'd like to thank you because this repo is a great example of how to integrate with Janus streaming plugin.

I noticed that your last commit is about adding video support. 

Were you able to make video streaming work? Only audio is working for me and It's been really hard to find references on how to make video streaming work.

**Comment by amarantedaniel** [comment]
If anyone out there is trying to set up video streaming using Janus and failing I got it working here: https://github.com/amarantedaniel/WebRTC-iOS/tree/integrate-with-janus

It's a bit of a mess and it uses a lot of code from this repo but it worked :)

**Comment by Igor-Khomich** [comment]
Hi, I already have the "video stream" working and "video room" is in progress. I will push the code in some days.
Sorry for late answer, haven't seen your previous comment.

**Comment by Igor-Khomich** [comment]
>make video streaming work

video stream works well, the only thing it's you should use the openGL render, the Metal one is not working for some reasons.

**Comment by amarantedaniel** [comment]
Hmm it wasn't working very well for me. 
One of the reasons was that when we call `self.webRTCClient!.renderRemoteVideo(to: remoteRenderer)` the `remoteStream` variable on WebRTCClient was not initialized yet. But I couldn't make it work even after fixing it.

**Comment by Igor-Khomich** [comment]
No, it's everything ok with remoteStream initialization. It's could be the server side settings, will check this with our admin
