### ISSUE TITLE
Hi. I have a question about video branch.

### ISSUE THREAD

**Issue by lygon55555** [Igor-Khomich/JanusAudioStreamPlayer#3]
Hi. I study WebRTC on iOS these days.
I saw your repo today and you are working on video room.
I think your code is awesome.
But on video branch, i couldn't build the project.
![스크린샷 2020-07-30 오후 2 41 25](https://user-images.githubusercontent.com/39911797/88885409-6f623300-d273-11ea-8d75-caa20935b3df.png)
Can you tell me how to fix these?

**Comment by Igor-Khomich** [comment]
hi, only the 'video stream' plugin is working now, 'video room' is in progress, will be ready in some days.
I have commented not working code, so you can build video branch now and try the "video stream".

**Comment by lygon55555** [comment]
@Igor-Khomich Oh, thank you so much! 
I'm looking forward to your new feature. Thanks again.

**Comment by antondityativ** [comment]
@lygon55555 Did you configure the app for the video room? Could you help me?

**Comment by Igor-Khomich** [comment]
Hi @antondityativ,
Yes, the "Video Bridge" tab works with "Video room" plugin.
To connect you have to type the room id and the streamer id.
To get this id's you need the following functions:
`
self.janusVBSession.getVideoRoomsList(completion: { (result, error) in
              print("GetStreamsList: \(String(describing: result))")
 })
                
let roomId: Int = 1234 //TODO: get correct room id
self.janusVBSession.getVideoRoomsParticipantsList(roomId: roomId) { (result, error) in
              print("getVideoRoomsParticipantsList: \(String(describing: result))")
}
`

Example of all this code is in the VideoBridgeViewController.swift file.

For now works on device only, I have plans to run it on the simulator, but I can't say exactly when, perhaps within a couple of weeks. It's something like "pet project", and I don't really have a lot of free time for it.

If there are any other questions, I will be glad to help you

**Comment by antondityativ** [comment]
@Igor-Khomich please follow this question: https://github.com/Igor-Khomich/JanusAudioStreamPlayer/issues/5
