### ISSUE TITLE
audiobridge can not get response when create offer

### ISSUE THREAD

**Issue by fukemy** [Igor-Khomich/JanusAudioStreamPlayer#8]
hi, after setlocaldescription, i send configure offer to server, but after check, i got "ack" action, not success response

```
responseJSON: Optional({
    janus = ack;
    "session_id" = 6841565447798616;
    transaction = 26RIyBjbZI3P;
})
```
can u help? Thanks

**Comment by Igor-Khomich** [comment]
@fukemy 
Hi, sorry, just saw your message.
Have you resolve the issue?

**Comment by fukemy** [comment]
i solved this using socket even instead of api janus, thanks
